// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kduxckpxghbrhlubyvxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkdXhja3B4Z2hicmhsdWJ5dnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjU5MjUsImV4cCI6MjA2MTEwMTkyNX0.yFLXVe-YXvIeF0uVQQbuO7ccLGP1VhpTF73gEQzq3B0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);